// app/components/layout/Sidebar.tsx
'use client';

import React from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import {
    LayoutDashboard,
    ShoppingCart,
    Users,
    Package,
    Settings,
    LogOut,
    Store,
    ChevronLeft,
    Menu
} from 'lucide-react';
import { Button } from '@/components/ui/button';

interface SidebarProps {
    className?: string;
    isOpen: boolean;
    onClose?: () => void;
}

const NAV_ITEMS = [
    {
        title: 'Dashboard',
        href: '/dashboard',
        icon: LayoutDashboard,
    },
    {
        title: 'POS',
        href: '/pos',
        icon: ShoppingCart,
    },
    {
        title: 'Orders',
        href: '/orders',
        icon: Package,
    },
    {
        title: 'Customers',
        href: '/customers',
        icon: Users,
    },
    {
        title: 'Inventory',
        href: '/inventory',
        icon: Store,
    },
    {
        title: 'Settings',
        href: '/settings',
        icon: Settings,
    },
];

export function Sidebar({ className, isOpen, onClose }: SidebarProps) {
    const pathname = usePathname();

    return (
        <>
            {/* Mobile Overlay */}
            <div
                className={cn(
                    "fixed inset-0 z-40 bg-black/50 backdrop-blur-sm transition-opacity md:hidden",
                    isOpen ? "opacity-100" : "opacity-0 pointer-events-none"
                )}
                onClick={onClose}
            />

            {/* Sidebar Container */}
            <aside
                className={cn(
                    "fixed top-0 left-0 z-40 h-screen w-64 bg-background border-r border-border transition-transform duration-300 md:translate-x-0",
                    isOpen ? "translate-x-0" : "-translate-x-full",
                    className
                )}
            >
                <div className="flex flex-col h-full">
                    {/* Logo Area */}
                    <div className="h-16 flex items-center px-6 border-b border-border">
                        <Link href="/dashboard" className="flex items-center gap-2 font-bold text-xl theme-logo">
                            <Store className="h-6 w-6" />
                            <span>Kemani POS</span>
                        </Link>
                    </div>

                    {/* Navigation */}
                    <div className="flex-1 py-4 overflow-y-auto">
                        <nav className="space-y-1 px-3">
                            {NAV_ITEMS.map((item) => (
                                <Link
                                    key={item.href}
                                    href={item.href}
                                    className={cn(
                                        "flex items-center gap-3 px-3 py-2.5 rounded-md text-sm font-medium transition-colors",
                                        pathname.startsWith(item.href)
                                            ? "bg-primary/10 text-primary"
                                            : "text-muted-foreground hover:bg-muted hover:text-foreground"
                                    )}
                                    onClick={() => onClose?.()}
                                >
                                    <item.icon className="h-5 w-5" />
                                    {item.title}
                                </Link>
                            ))}
                        </nav>
                    </div>

                    {/* Footer Area */}
                    <div className="p-4 border-t border-border">
                        <Button variant="ghost" className="w-full justify-start gap-3 text-red-500 hover:text-red-600 hover:bg-red-50 dark:hover:bg-red-950/20">
                            <LogOut className="h-5 w-5" />
                            Sign Out
                        </Button>
                    </div>
                </div>
            </aside>
        </>
    );
}

// apps/pos_sveltekit/src/lib/components/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import {
		LayoutDashboard, Package, Users, ShoppingCart, BarChart3, Settings, 
		Store, LogOut, MessageSquare, Briefcase, Building, ClipboardList
	} from 'lucide-svelte';

	let { tenant, userData, email, handleLogout, onnavclick = (e: any) => {} } = $props<any>();

	let navigation = $derived([
		{ name: 'Dashboard', href: '/', icon: LayoutDashboard, visible: true },
		{ name: 'POS', href: '/pos', icon: Store, visible: userData?.canManagePOS ?? false },
		{ name: 'Products', href: '/products', icon: Package, visible: userData?.canManageProducts ?? false },
		{ name: 'Customers', href: '/customers', icon: Users, visible: userData?.['canManage Customers'] ?? false },
		{ name: 'Orders', href: '/orders', icon: ShoppingCart, visible: userData?.canManageOrders ?? false },
		{ name: 'Inventory', href: '/inventory', icon: ClipboardList, visible: userData?.canManageInventory ?? false },
		{ name: 'Staffs', href: '/staffs', icon: Briefcase, visible: userData?.canMangeStaff ?? false },
		{ name: 'Messages', href: '/messages', icon: MessageSquare, visible: userData?.canViewMessages ?? false },
		{ name: 'Branches', href: '/branches', icon: Building, visible: userData?.canManagebranches ?? false },
		{ name: 'Analytics', href: '/analytics', icon: BarChart3, visible: userData?.canViewAnalytics ?? false },
		{ name: 'Settings', href: '/settings', icon: Settings, visible: true }
	].filter(item => item.visible));

	function getInitial(emailStr: string | undefined): string {
		return emailStr ? emailStr.charAt(0).toUpperCase() : 'U';
	}
</script>

<div class="flex flex-col h-full bg-white">
	<!-- Brand -->
	<div class="p-4 border-b shrink-0">
		<h1 class="text-xl font-bold text-gray-900">{tenant?.name || 'Kemani POS'}</h1>
		<p class="text-sm text-gray-500">Business Dashboard</p>
	</div>

	<!-- Navigation -->
	<nav class="p-4 space-y-1 flex-1 overflow-y-auto min-h-0" style="max-height: calc(100vh - 160px);">
		{#each navigation as item}
			{@const Icon = item.icon}
			<a
				href={item.href}
				onclick={onnavclick}
				class="flex items-center gap-3 px-3 py-2 rounded-md transition-colors {$page.url.pathname === item.href ? 'bg-indigo-50 text-indigo-700 font-medium' : 'text-gray-700 hover:bg-gray-100'}"
			>
				<Icon class="h-5 w-5" />
				{item.name}
			</a>
		{/each}
	</nav>

	<!-- Profile and Logout -->
	<div class="p-4 border-t flex flex-col gap-4 shrink-0">
		<!-- User Profile -->
		<div class="flex items-center gap-3">
			{#if userData?.profile_picture_url}
				<img src={userData.profile_picture_url} alt="Profile" class="h-9 w-9 rounded-full object-cover border border-gray-200 shadow-sm" />
			{:else}
				<div class="h-9 w-9 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-700 font-bold border border-indigo-200">
					{getInitial(email)}
				</div>
			{/if}
			<div class="flex-1 min-w-0">
				<p class="text-sm font-bold text-gray-900 truncate">{userData?.full_name || 'User'}</p>
				<p class="text-[10px] text-gray-500 truncate">{email || ''}</p>
			</div>
		</div>

		<button
			onclick={handleLogout}
			class="w-full flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-white bg-red-600 hover:bg-red-700 rounded-md transition-colors"
		>
			<LogOut class="h-4 w-4" />
			Logout
		</button>
	</div>
</div>
