// app/(auth)/login/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, Mail } from 'lucide-react';

export default function LoginPage() {
    const [identifier, setIdentifier] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    const router = useRouter();

    const handleSendOTP = async (e: React.FormEvent) => {
        e.preventDefault();
        setError('');
        setLoading(true);

        try {
            const response = await fetch('/api/auth/send-otp', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    identifier,
                    type: 'email',
                }),
            });

            const data = await response.json();

            if (!response.ok) {
                setError(data.error || 'Failed to send OTP');
                setLoading(false);
                return;
            }

            // Navigate to OTP verification page
            router.push(`/verify-otp?identifier=${encodeURIComponent(data.identifier)}&type=email`);
        } catch (err) {
            setError('Something went wrong. Please try again.');
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-gradient-to-b from-emerald-950 via-green-900 to-gray-900 flex items-center justify-center px-4">
            <div className="w-full max-w-md">
                {/* Logo */}
                <div className="text-center mb-8">
                    <Link href="/" className="inline-flex items-center">
                        <span className="text-3xl font-bold text-emerald-400">Kemani</span>
                        <span className="ml-2 text-lg text-emerald-300/70">POS</span>
                    </Link>
                    <p className="mt-2 text-emerald-100/70">Sign in with email</p>
                </div>

                {/* Login Card */}
                <div className="bg-white/5 backdrop-blur-md rounded-2xl p-8 border border-emerald-500/20">
                    <form onSubmit={handleSendOTP}>
                        {/* Input Field */}
                        <div className="mb-6">
                            <label htmlFor="identifier" className="block text-sm font-medium text-emerald-100 mb-2">
                                Email Address
                            </label>
                            <div className="relative">
                                <Mail className="absolute left-3 top-3.5 h-5 w-5 text-emerald-300/50" />
                                <input
                                    id="identifier"
                                    type="email"
                                    value={identifier}
                                    onChange={(e) => setIdentifier(e.target.value)}
                                    placeholder="you@example.com"
                                    className="w-full pl-10 pr-4 py-3 bg-white/10 border border-emerald-500/30 rounded-lg text-white placeholder-emerald-300/40 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
                                    required
                                />
                            </div>
                        </div>

                        {/* Error Message */}
                        {error && (
                            <div className="mb-4 p-3 bg-red-500/20 border border-red-500/50 rounded-lg text-red-200 text-sm">
                                {error}
                            </div>
                        )}

                        {/* Submit Button */}
                        <button
                            type="submit"
                            disabled={loading}
                            className="w-full flex items-center justify-center gap-2 px-6 py-3 bg-gradient-to-r from-emerald-600 to-green-600 text-white font-semibold rounded-lg hover:from-emerald-500 hover:to-green-500 transition shadow-lg shadow-emerald-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {loading ? 'Sending...' : 'Send Verification Code'}
                            {!loading && <ArrowRight className="h-5 w-5" />}
                        </button>
                    </form>

                    {/* Divider */}
                    <div className="my-6 flex items-center">
                        <div className="flex-1 border-t border-emerald-500/20"></div>
                        <span className="px-4 text-sm text-emerald-100/50">or</span>
                        <div className="flex-1 border-t border-emerald-500/20"></div>
                    </div>

                    {/* Register Link */}
                    <div className="text-center">
                        <p className="text-emerald-100/70 text-sm">
                            New to Kemani?{' '}
                            <span className="text-emerald-300">Just enter your email above to setup an account.</span>
                        </p>
                    </div>
                </div>

                {/* Back to Home */}
                <div className="mt-6 text-center">
                    <Link href="/" className="text-emerald-300/70 hover:text-emerald-300 text-sm">
                        ← Back to home
                    </Link>
                </div>
            </div>
        </div>
    );
}

// apps/healthcare_customer/src/routes/auth/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Mail, Lock, Eye, EyeOff, AlertCircle } from 'lucide-svelte';
	import { authStore } from '$lib/stores/auth.svelte';

	let email = $state('');
	let password = $state('');
	let showPassword = $state(false);
	let isLoading = $state(false);
	let error = $state('');

	async function handleSubmit(e: Event) {
		e.preventDefault();
		error = '';
		isLoading = true;

		try {
			await authStore.signIn(email, password);
			goto('/');
		} catch (err: any) {
			error = err.message || 'Failed to sign in. Please check your credentials.';
		} finally {
			isLoading = false;
		}
	}
</script>

<svelte:head>
	<title>Login | Kemani Health</title>
</svelte:head>

<div class="min-h-screen bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center px-4">
	<div class="max-w-md w-full">
		<!-- Logo/Header -->
		<div class="text-center mb-8">
			<div class="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-blue-500 to-blue-600 rounded-2xl mb-4">
				<span class="text-2xl font-bold text-white">K</span>
			</div>
			<h1 class="text-3xl font-bold text-gray-900">Welcome Back</h1>
			<p class="text-gray-600 mt-2">Sign in to access your health portal</p>
		</div>

		<!-- Login Form -->
		<div class="bg-white rounded-2xl shadow-xl p-8">
			<form onsubmit={handleSubmit} class="space-y-6">
				<!-- Email -->
				<div>
					<label for="email" class="block text-sm font-medium text-gray-700 mb-2">
						Email Address
					</label>
					<div class="relative">
						<div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
							<Mail class="h-5 w-5 text-gray-400" />
						</div>
						<input
							id="email"
							type="email"
							bind:value={email}
							required
							class="block w-full pl-10 pr-3 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
							placeholder="you@example.com"
						/>
					</div>
				</div>

				<!-- Password -->
				<div>
					<label for="password" class="block text-sm font-medium text-gray-700 mb-2">
						Password
					</label>
					<div class="relative">
						<div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
							<Lock class="h-5 w-5 text-gray-400" />
						</div>
						<input
							id="password"
							type={showPassword ? 'text' : 'password'}
							bind:value={password}
							required
							class="block w-full pl-10 pr-10 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
							placeholder="Enter your password"
						/>
						<button
							type="button"
							onclick={() => showPassword = !showPassword}
							class="absolute inset-y-0 right-0 pr-3 flex items-center"
						>
							{#if showPassword}
								<EyeOff class="h-5 w-5 text-gray-400" />
							{:else}
								<Eye class="h-5 w-5 text-gray-400" />
							{/if}
						</button>
					</div>
				</div>

				<!-- Error Message -->
				{#if error}
					<div class="bg-red-50 border border-red-200 rounded-lg p-4 flex items-start gap-3">
						<AlertCircle class="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
						<p class="text-sm text-red-700">{error}</p>
					</div>
				{/if}

				<!-- Forgot Password -->
				<div class="flex items-center justify-between">
					<label class="flex items-center">
						<input type="checkbox" class="rounded border-gray-300 text-blue-600 focus:ring-blue-500" />
						<span class="ml-2 text-sm text-gray-600">Remember me</span>
					</label>
					<a href="/auth/reset-password" class="text-sm text-blue-600 hover:underline">
						Forgot password?
					</a>
				</div>

				<!-- Submit Button -->
				<button
					type="submit"
					disabled={isLoading}
					class="w-full py-3 px-4 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
				>
					{#if isLoading}
						<span class="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
						<span>Signing in...</span>
					{:else}
						<span>Sign In</span>
					{/if}
				</button>
			</form>

			<!-- Sign Up Link -->
			<div class="mt-6 text-center">
				<p class="text-sm text-gray-600">
					Don't have an account?
					<a href="/auth/signup" class="text-blue-600 hover:underline font-medium">
						Create account
					</a>
				</p>
			</div>
		</div>

		<!-- Footer -->
		<p class="text-center text-sm text-gray-600 mt-8">
			By signing in, you agree to our
			<a href="/terms" class="text-blue-600 hover:underline">Terms of Service</a>
			and
			<a href="/privacy" class="text-blue-600 hover:underline">Privacy Policy</a>
		</p>
	</div>
</div>
